apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: secure-container
    image: nginx:1.19.0
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true